# Generated by Django 3.2.14 on 2022-08-02 08:58

from django.db import migrations, models
import django.db.models.deletion

import wagtail.documents.blocks
import wagtail.snippets.blocks
import wagtail_dottedimage.blocks
import wagtailplugin.home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Город')),
                ('i18n_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Перевод')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('country_name', models.CharField(max_length=50, verbose_name='Страна')),
                ('country_code', models.CharField(max_length=5, verbose_name='Код страны')),
                ('timezone', models.CharField(max_length=50, verbose_name='Time zone')),
                ('default', models.BooleanField(default=False, verbose_name='По-умолчанию')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'Города',
                'ordering': ['-default', 'country_name', '-i18n_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('color', models.CharField(choices=[('#ED1B35', 'Красная (Сокольническая)'), ('#44B85C', 'Зеленая (Замоскворецкая)'), ('#0078BF', 'Синяя (Арбатско-Покровская)'), ('#19C1F3', 'Голубая (Филёвская)'), ('#894E35', 'Кольцевая'), ('#F58631', 'Рыжая (Калужско-Рижская)'), ('#8E479C', 'Фиолетовая (Таганско-Краснопресненская)'), ('#FFCB31', 'Желтая (Калининско-Солнцевская)'), ('#A1A2A3', 'Серая (Серпуховско-Тимирязевская)'), ('#B3D445', 'Салатовая (Люблинско-Дмитровская)'), ('#79CDCD', 'Бирюзовая (Каховская)'), ('#ACBFE1', 'Серо-голубой (Бутовская)'), ('#de942b', 'Оранжевая (Белорусско-Савёловский)'), ('#d23973', 'Красноватая (Курско-Рижский)')], default='#ED1B35', max_length=7, verbose_name='Цвет ветки')),
            ],
            options={
                'verbose_name': 'метро',
                'verbose_name_plural': 'Метро',
                'ordering': ['title'],
            },
            bases=(wagtailplugin.home.models.SearchMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MetroMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dots', wagtail.core.fields.StreamField([('map', wagtail.core.blocks.StructBlock([('image', wagtail_dottedimage.blocks.BigImageChooserBlock()), ('dots', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('coords', wagtail.core.blocks.CharBlock(default='50%,50%', label='Коорд.')), ('metro', wagtail.snippets.blocks.SnippetChooserBlock(wagtailplugin.home.models.Metro, label='Станция'))]), label='Точки')), ('svg', wagtail.documents.blocks.DocumentChooserBlock(label='SVG', required=False))]))], blank=True, null=True,verbose_name='Карта и точки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metro', to='home.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'карта',
                'verbose_name_plural': 'Карты метро',
                'ordering': ['city'],
            },
        ),
    ]
