# Generated by Django 3.1.14 on 2022-08-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_city_metro_metromap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-i18n_name', 'name'], 'verbose_name': 'город', 'verbose_name_plural': 'Города'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='default',
        ),
        migrations.RemoveField(
            model_name='city',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metromap',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
